kind: pipeline
name: node-v10
type: docker

platform:
    os: linux
    arch: amd64

steps:
    -   name: install
        image: node:10
        commands:
            - npm i --no-save --quiet --no-optional
            - npm run test
    -   name: tests
        image: node:10
        commands:
            - npm run test

trigger:
    branch:
        - master
        - drone
    event:
        exclude:
            - cron

---
kind: pipeline
name: node-v12
type: docker

platform:
    os: linux
    arch: amd64

steps:
    -   name: install
        image: node:12
        commands:
            - npm i --no-save --quiet --no-optional
            - npm run test
    -   name: tests
        image: node:12
        commands:
            - npm run test

trigger:
    branch:
        - master
        - drone
    event:
        exclude:
            - cron

---
kind: pipeline
name: deps
type: docker

platform:
    os: linux
    arch: amd64

steps:
    -   name: install
        image: node:12
        commands:
            - npm i --no-save --quiet --no-optional
        depends_on: [ clone ]
    -   name: audit
        image: node:12
        commands:
            - npm audit
        depends_on: [ clone ]
    -   name: outdated
        image: node:12
        commands:
            - npm run check-outdated
        depends_on: [ install ]

trigger:
    branch:
        - master
