name: compliance

on:
    pull_request:
        branches:
            - master
        types: [ opened, synchronize, reopened ]

jobs:
    linter:
        runs-on: ubuntu-24.04
        steps:
            -   name: Checkout
                uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
            -   name: Set up PNPM package manager
                uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4
            -   name: Set up NodeJS
                uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
                with:
                    node-version: 22
                    cache: pnpm
            -   name: Install dependencies
                run: pnpm install
            -   name: Compile
                run: pnpm build:ts
            -   name: ESLint
                run: pnpm lint:eslint
            -   name: Prettier
                run: pnpm lint:prettier